"""Shared Pydantic models for AI analysis outputs.

Design principle (from CLAUDE.md):
  - AI ONLY summarizes and analyzes — it NEVER computes numbers
  - All structured outputs use Pydantic for validation and schema enforcement
  - These models are the single source of truth for AI response shapes
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class AIAnalysisOutput(BaseModel):
    """Structured output for a single-signal or symbol-level AI analysis.

    Returned by AIAnalyst.analyze_signal() and the /reports/analyze endpoint.
    All text fields are populated by the LLM; all numeric fields are validated
    by Pydantic so the frontend can render them safely.
    """

    conclusion: str = Field(
        max_length=300,
        description="核心结论（中文）：一句话总结当前信号的交易含义，引用提供的数据，不要自己计算",
    )
    conclusion_en: str = Field(
        default="",
        max_length=300,
        description="Core conclusion (English): one-sentence summary of the signal's trading implication, citing provided data only",
    )
    time_horizon: str = Field(
        max_length=20,
        description="建议持仓时间维度，例如 '1-5天' / '1-4周' / '1-3月'",
    )
    supporting_evidence: Annotated[list[str], Field(max_length=5)] = Field(
        description="支撑该结论的关键证据，每条不超过 80 字，最多 5 条",
    )
    risk_evidence: Annotated[list[str], Field(max_length=3)] = Field(
        description="主要风险点，每条不超过 80 字，最多 3 条",
    )
    invalidation_conditions: Annotated[list[str], Field(max_length=3)] = Field(
        description="信号失效条件：哪些情况出现时应放弃该信号，最多 3 条",
    )
    suggested_strategies: Annotated[list[str], Field(max_length=3)] = Field(
        description="适配的操作策略（仅供参考，非投资建议），最多 3 条",
    )
    historical_performance_summary: str = Field(
        max_length=200,
        description="历史上类似信号组合的表现概述（如无历史数据，说明原因）",
    )
    risk_level: Literal["low", "medium", "high", "very_high"] = Field(
        description="综合风险等级：low / medium / high / very_high",
    )
    confidence_score: float = Field(
        ge=0,
        le=100,
        description="AI 对此次分析结论的置信度，0-100 整数",
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="生成时间 ISO 8601",
    )


# ── Desk Consensus Models ──────────────────────────────────────────────────────


class StrategyFit(BaseModel):
    """Strategy fit assessment for a single stock, within a DeskConsensus."""

    strategy_name: str = Field(description="策略名称（中文）")
    strategy_name_en: str = Field(description="Strategy name (English)")
    fit_score: float = Field(ge=0, le=100, description="当前市场/股票与该策略的契合度，0-100")
    reason: str = Field(max_length=150, description="契合/不契合的核心原因（中文）")
    reason_en: str = Field(max_length=150, description="Core reason for fit/no-fit (English)")


class DeskConsensus(BaseModel):
    """Multi-desk unified consensus for a single stock.

    Aggregates Technical / Flow / Event / Risk desk opinions into a single
    structured verdict. Generated by AIAnalyst.analyze_desk().
    """

    # ── Final verdict ──────────────────────────────────────────────
    conclusion: str = Field(max_length=300, description="最终综合结论（中文）")
    conclusion_en: str = Field(max_length=300, description="Final combined conclusion (English)")
    final_action: Literal[
        "strong_buy", "buy", "hold", "watch", "sell", "strong_sell", "avoid"
    ] = Field(description="最终操作建议")
    conviction: Literal["high", "medium", "low"] = Field(description="综合确信度")
    time_horizon: str = Field(max_length=20, description="建议持仓时间，如 '1-5天'")
    risk_level: Literal["low", "medium", "high", "very_high"] = Field(description="综合风险等级")
    confidence_score: float = Field(ge=0, le=100, description="AI 置信度 0-100")

    # ── Evidence chains ────────────────────────────────────────────
    supporting_evidence: Annotated[list[str], Field(max_length=5)] = Field(
        description="支撑结论的关键证据（最多5条，每条≤80字，中文）"
    )
    supporting_evidence_en: Annotated[list[str], Field(max_length=5)] = Field(
        default_factory=list,
        description="Key supporting evidence (up to 5 items, English)"
    )
    risk_evidence: Annotated[list[str], Field(max_length=3)] = Field(
        description="主要风险点（最多3条，每条≤80字，中文）"
    )
    risk_evidence_en: Annotated[list[str], Field(max_length=3)] = Field(
        default_factory=list,
        description="Key risk factors (up to 3 items, English)"
    )
    invalidation_conditions: Annotated[list[str], Field(max_length=3)] = Field(
        description="信号失效条件（最多3条，中文）"
    )
    invalidation_conditions_en: Annotated[list[str], Field(max_length=3)] = Field(
        default_factory=list,
        description="Signal invalidation conditions (up to 3 items, English)"
    )

    # ── Four desk assessments ──────────────────────────────────────
    technical_desk: str = Field(max_length=250, description="技术分析台观点（中文）")
    technical_desk_en: str = Field(max_length=250, description="Technical Desk view (English)")
    flow_desk: str = Field(max_length=250, description="资金流向台观点（中文）")
    flow_desk_en: str = Field(max_length=250, description="Flow Desk view (English)")
    event_desk: str = Field(max_length=250, description="事件驱动台观点（中文）")
    event_desk_en: str = Field(max_length=250, description="Event Desk view (English)")
    risk_desk: str = Field(max_length=250, description="风险管理台观点（中文）")
    risk_desk_en: str = Field(max_length=250, description="Risk Desk view (English)")

    # ── Strategy fit ───────────────────────────────────────────────
    strategy_fit: Annotated[list[StrategyFit], Field(max_length=4)] = Field(
        description="最多4个适配策略的契合度评分"
    )

    generated_at: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="生成时间 ISO 8601",
    )


# ── Portfolio Builder Models ───────────────────────────────────────────────────


class PortfolioPreferences(BaseModel):
    """User preferences for AI portfolio construction."""

    user_id: str
    risk_preference: Literal[
        "conservative", "moderate", "balanced", "aggressive", "speculative"
    ]
    max_drawdown_pct: float = Field(ge=5, le=25)
    return_preference: str  # e.g. "capital_preservation" | "income" | "balanced" | "growth"
    holding_period: str     # e.g. "intraday" | "1-5d" | "1-4w" | "1-3m" | "6m+"
    trading_style: str      # e.g. "trend" | "momentum" | "mean_reversion" | "event" | "value" | "quant"
    universe: str           # e.g. "us_etf" | "us_large" | "us_all" | "global"
    sector_preferences: list[str] = Field(default_factory=list)
    risk_limits: dict = Field(default_factory=dict)


class PortfolioRecommendation(BaseModel):
    """Full AI-generated portfolio recommendation."""

    portfolio_type: str
    portfolio_type_en: str
    regime_at_creation: str
    risk_level: str
    confidence_score: float = Field(ge=0, le=100)
    recommended_templates: list[str] = Field(default_factory=list)
    allocation_structure: dict = Field(default_factory=dict)
    core_candidates: list[dict] = Field(default_factory=list)
    enhance_candidates: list[dict] = Field(default_factory=list)
    satellite_candidates: list[dict] = Field(default_factory=list)
    watchlist_candidates: list[dict] = Field(default_factory=list)
    avoid_candidates: list[dict] = Field(default_factory=list)
    backtest_summary: dict = Field(default_factory=dict)
    ai_explanation: str = ""
    ai_explanation_en: str = ""
