#!/usr/bin/env node
/**
 * Generate src/content/manual/_generated.ts from all .md files in
 * src/content/manual/. Runs as npm prebuild (and pre dev) so the help
 * center always has fresh content without any runtime fs.readFileSync.
 *
 * Output format:
 *   export const MANUAL_FILES = {
 *     "00-overview": "...markdown body...",
 *     "L2-01-dashboard": "...",
 *   };
 *
 * The manual content lives in plain .md files (single source of truth);
 * this generator just inlines them into a TS module for build-time
 * bundling. Cross-bundler safe (webpack / Turbopack / esbuild / etc).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const MANUAL_DIR = path.join(REPO_ROOT, "src", "content", "manual");
const OUT_FILE = path.join(MANUAL_DIR, "_generated.ts");

function escapeForTemplateLiteral(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  if (!fs.existsSync(MANUAL_DIR)) {
    console.error(`[generate-manual] Manual dir not found: ${MANUAL_DIR}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(MANUAL_DIR)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();

  if (files.length === 0) {
    console.warn("[generate-manual] No manual files found.");
  }

  const entries = files.map((file) => {
    const slug = file.replace(/\.md$/, "");
    const body = fs.readFileSync(path.join(MANUAL_DIR, file), "utf-8");
    return { slug, body };
  });

  const lines = [
    "// AUTO-GENERATED by scripts/generate-manual.mjs — do NOT edit by hand.",
    "// Source files: src/content/manual/*.md",
    "// Regenerate: `npm run generate:manual` (also runs via prebuild + predev hooks).",
    "",
    "/** Raw markdown body keyed by slug. */",
    "export const MANUAL_FILES: Record<string, string> = {",
  ];
  for (const { slug, body } of entries) {
    lines.push(`  "${slug}": \`${escapeForTemplateLiteral(body)}\`,`);
  }
  lines.push("};");
  lines.push("");

  fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf-8");
  console.log(
    `[generate-manual] Wrote ${entries.length} entries → ${path.relative(REPO_ROOT, OUT_FILE)}`,
  );
}

main();
